### ISSUE TITLE
Some create methods in models don't work any more

### ISSUE THREAD

**Issue by silvasur** [silvasur/ratatoeskr-cms#8]
At least in my local installation, MariaDB doesn't accept some of those INSERTs with missing values. E.g. I get the following error during setup:

```
[Mon Apr 27 20:04:45 2020] [::1]:52130 [500]: POST /setup.php?lang=en - Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'baseurl' doesn't have a default value in /home/laria/src/r7r/ratatoeskr-cms/ratatoeskr/sys/db.php:88
Stack trace:
#0 /home/laria/src/r7r/ratatoeskr-cms/ratatoeskr/sys/db.php(88): PDOStatement->execute()
#1 /home/laria/src/r7r/ratatoeskr-cms/ratatoeskr/sys/models.php(2521): qdb()
#2 /home/laria/src/r7r/ratatoeskr-cms/ratatoeskr/setup/setup.php(230): Repository::create()
#3 /home/laria/src/r7r/ratatoeskr-cms/setup.php(207): require_once('/home/laria/src...')
#4 {main}
  thrown in /home/laria/src/r7r/ratatoeskr-cms/ratatoeskr/sys/db.php on line 88
```

**Comment by silvasur** [comment]
Repository::create was fixed in 3f7cbc9. The others might be fine, but I need to check
